import type { Metadata } from "next";
import { Roboto_Serif, Poppins } from "next/font/google";
import "./globals.css";

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Ensure correct weights
  display: "swap",
});

export const metadata: Metadata = {
  title: "ZipBuy",
  description: "Generated by create next app",
  icons: {
    icon: "/_Orange Modern Logo-modified.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${robotoSerif.variable}`}>
      <head>
        {/* Preload CSS file with 'as="style"' */}
        <link
          rel="preload"
          href="/_next/static/css/f43265502ba628c8.css"
          as="style"
          type="text/css"
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
